import { useState, useEffect } from 'react';
import { Modal } from '@/components/ui/Modal';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import {
    useCreateAssessmentMutation,
    useGetTermsQuery,
    useGetTeacherSubjectsQuery,
    type AssessmentType,
    type QuestionType
} from '@/lib/store/api/schoolAdminApi';
import { useGenerateAssessmentMutation } from '@/lib/store/api/aiApi';
import { toast } from 'react-hot-toast';
import { Trash2, Plus, Sparkles, Loader2 } from 'lucide-react';

interface CreateAssessmentModalProps {
    isOpen: boolean;
    onClose: () => void;
    schoolId: string;
    classId: string;
    activeTermId?: string;
    subjectId?: string;
}

interface Question {
    text: string;
    type: QuestionType;
    options: string[];
    correctAnswer: string;
    points: number;
    order: number;
}

export function CreateAssessmentModal({ isOpen, onClose, schoolId, classId, activeTermId, subjectId }: CreateAssessmentModalProps) {
    const [createAssessment, { isLoading: isCreating }] = useCreateAssessmentMutation();
    const [generateAiAssessment, { isLoading: isGeneratingAi }] = useGenerateAssessmentMutation();
    const { data: termsResponse } = useGetTermsQuery({ schoolId });
    // Assuming we need the teacher's profile ID or just the schoolId to get subjects
    const { data: subjectsResponse } = useGetTeacherSubjectsQuery({ schoolId, teacherId: 'me' }); // 'me' might be handled by backend if token is present

    const [title, setTitle] = useState('');
    const [description, setDescription] = useState('');
    const [type, setType] = useState<AssessmentType>('QUIZ');
    const [termId, setTermId] = useState(activeTermId || '');
    const [selectedSubjectId, setSelectedSubjectId] = useState(subjectId || '');
    const [dueDate, setDueDate] = useState('');
    const [maxScore, setMaxScore] = useState(100);
    const [questions, setQuestions] = useState<Question[]>([]);

    // AI Generation state
    const [aiTopic, setAiTopic] = useState('');
    const [aiCount, setAiCount] = useState(10);
    const [useAi, setUseAi] = useState(false);

    useEffect(() => {
        if (activeTermId) setTermId(activeTermId);
        if (subjectId) setSelectedSubjectId(subjectId);
    }, [activeTermId, subjectId, isOpen]);

    const addQuestion = () => {
        setQuestions([
            ...questions,
            {
                text: '',
                type: 'MULTIPLE_CHOICE',
                options: ['', '', '', ''],
                correctAnswer: '',
                points: 1,
                order: questions.length
            }
        ]);
    };

    const removeQuestion = (index: number) => {
        const newQuestions = [...questions];
        newQuestions.splice(index, 1);
        // Re-order
        const reordered = newQuestions.map((q, i) => ({ ...q, order: i }));
        setQuestions(reordered);
    };

    const updateQuestion = (index: number, field: keyof Question, value: any) => {
        const newQuestions = [...questions];
        newQuestions[index] = { ...newQuestions[index], [field]: value };
        setQuestions(newQuestions);
    };

    const handleAiGenerate = async () => {
        if (!aiTopic) {
            toast.error('Please enter a topic for AI generation');
            return;
        }

        const subjectName = subjectsResponse?.data?.find(s => s.id === selectedSubjectId)?.name || 'General';

        try {
            const result = await generateAiAssessment({
                schoolId,
                body: {
                    topic: aiTopic,
                    subject: subjectName,
                    gradeLevel: 'Class ' + classId, // Simplified for now
                    questionCount: aiCount,
                    questionTypes: ['multiple_choice', 'short_answer'],
                    difficulty: 'medium'
                }
            }).unwrap();

            if (result && result.questions) {
                const aiQuestions = result.questions.map((q: any, i: number) => ({
                    text: q.question,
                    type: q.type === 'multiple_choice' ? 'MULTIPLE_CHOICE' : (q.type === 'short_answer' ? 'SHORT_ANSWER' : 'ESSAY'),
                    options: q.options || [],
                    correctAnswer: q.correctAnswer,
                    points: q.points || 1,
                    order: i
                }));
                setQuestions(aiQuestions);
                setUseAi(false);
                toast.success('Questions generated by AI!');
            }
        } catch (error: any) {
            toast.error(error?.data?.message || 'Failed to generate AI questions. Ensure you have enough credits.');
        }
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        if (!selectedSubjectId) {
            toast.error('Please select a subject');
            return;
        }

        if (questions.length === 0) {
            toast.error('Please add at least one question');
            return;
        }

        try {
            await createAssessment({
                schoolId,
                classId,
                dto: {
                    title,
                    description,
                    type,
                    subjectId: selectedSubjectId,
                    termId,
                    dueDate,
                    maxScore,
                    questions: questions.map(q => ({
                        ...q,
                        options: q.type === 'MULTIPLE_CHOICE' ? q.options : undefined
                    }))
                }
            }).unwrap();

            toast.success('Assessment created successfully!');
            onClose();
            // Reset form
            setTitle('');
            setDescription('');
            setQuestions([]);
        } catch (error: any) {
            toast.error(error?.data?.message || 'Failed to create assessment');
        }
    };

    return (
        <Modal
            isOpen={isOpen}
            onClose={onClose}
            title="Create Assessment"
            size="xl"
            scrollable
        >
            <form onSubmit={handleSubmit} className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="md:col-span-2">
                        <label className="block text-sm font-semibold mb-1">Title</label>
                        <Input
                            placeholder="e.g. Mid-Term Mathematics Quiz"
                            value={title}
                            onChange={(e) => setTitle(e.target.value)}
                            required
                        />
                    </div>

                    <div>
                        <label className="block text-sm font-semibold mb-1">Subject</label>
                        <select
                            value={selectedSubjectId}
                            onChange={(e) => setSelectedSubjectId(e.target.value)}
                            className="w-full h-10 rounded-md border border-light-border dark:border-dark-border bg-transparent px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                            required
                        >
                            <option value="">Select Subject</option>
                            {subjectsResponse?.data?.map((subject) => (
                                <option key={subject.id} value={subject.id}>
                                    {subject.name}
                                </option>
                            ))}
                        </select>
                    </div>

                    <div>
                        <label className="block text-sm font-semibold mb-1">Academic Term</label>
                        <select
                            value={termId}
                            onChange={(e) => setTermId(e.target.value)}
                            className="w-full h-10 rounded-md border border-light-border dark:border-dark-border bg-transparent px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                            required
                        >
                            <option value="">Select Term</option>
                            {termsResponse?.data?.items?.map((term: any) => (
                                <option key={term.id} value={term.id}>
                                    {term.name}
                                </option>
                            )) || termsResponse?.map((term: any) => (
                                <option key={term.id} value={term.id}>
                                    {term.name}
                                </option>
                            ))}
                        </select>
                    </div>

                    <div>
                        <label className="block text-sm font-semibold mb-1">Assessment Type</label>
                        <select
                            value={type}
                            onChange={(e) => setType(e.target.value as AssessmentType)}
                            className="w-full h-10 rounded-md border border-light-border dark:border-dark-border bg-transparent px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                            required
                        >
                            <option value="QUIZ">Quiz</option>
                            <option value="EXAM">Exam</option>
                            <option value="ASSIGNMENT">Assignment</option>
                        </select>
                    </div>

                    <div>
                        <label className="block text-sm font-semibold mb-1">Max Score</label>
                        <Input
                            type="number"
                            value={maxScore}
                            onChange={(e) => setMaxScore(Number(e.target.value))}
                            required
                        />
                    </div>

                    <div>
                        <label className="block text-sm font-semibold mb-1">Due Date (Optional)</label>
                        <Input
                            type="date"
                            value={dueDate}
                            onChange={(e) => setDueDate(e.target.value)}
                        />
                    </div>
                </div>

                {/* AI Helper Toggle */}
                <div className="p-4 border border-blue-200 dark:border-blue-800 bg-blue-50/50 dark:bg-blue-900/20 rounded-xl">
                    <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center gap-2 text-blue-600 dark:text-blue-400">
                            <Sparkles className="h-5 w-5" />
                            <h3 className="font-bold">AI Assessment Generator</h3>
                        </div>
                        <Button
                            type="button"
                            variant="outline"
                            size="sm"
                            onClick={() => setUseAi(!useAi)}
                            className="border-blue-200 dark:border-blue-800 text-blue-600 dark:text-blue-400"
                        >
                            {useAi ? 'Hide' : 'Use AI Helper'}
                        </Button>
                    </div>

                    {useAi && (
                        <div className="space-y-4 mt-4 animate-in fade-in slide-in-from-top-2">
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-xs font-semibold mb-1 uppercase tracking-wider opacity-70">Topic to cover</label>
                                    <Input
                                        placeholder="e.g. Quadratic Equations, Photosynthesis..."
                                        value={aiTopic}
                                        onChange={(e) => setAiTopic(e.target.value)}
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs font-semibold mb-1 uppercase tracking-wider opacity-70">Number of Questions</label>
                                    <Input
                                        type="number"
                                        value={aiCount}
                                        onChange={(e) => setAiCount(Number(e.target.value))}
                                        min={1}
                                        max={30}
                                    />
                                </div>
                            </div>
                            <Button
                                type="button"
                                className="w-full bg-blue-600 hover:bg-blue-700 text-white gap-2"
                                onClick={handleAiGenerate}
                                isLoading={isGeneratingAi}
                            >
                                <Sparkles className="h-4 w-4" />
                                Generate Questions with AI
                            </Button>
                            <p className="text-[10px] text-center text-light-text-secondary dark:text-dark-text-secondary">
                                This will use tokens from your school's subscription. You can edit the resulting questions manually.
                            </p>
                        </div>
                    )}
                </div>

                {/* Questions Section */}
                <div>
                    <div className="flex items-center justify-between mb-4">
                        <h3 className="font-bold text-lg">Questions ({questions.length})</h3>
                        <Button type="button" variant="outline" size="sm" onClick={addQuestion}>
                            <Plus className="h-4 w-4 mr-2" /> Add Question
                        </Button>
                    </div>

                    <div className="space-y-6">
                        {questions.map((q, idx) => (
                            <div key={idx} className="p-4 border border-light-border dark:border-dark-border rounded-xl bg-light-surface/50 dark:bg-dark-surface/50 relative group">
                                <Button
                                    type="button"
                                    variant="ghost"
                                    size="icon"
                                    className="absolute top-2 right-2 text-red-500 opacity-0 group-hover:opacity-100 transition-opacity"
                                    onClick={() => removeQuestion(idx)}
                                >
                                    <Trash2 className="h-4 w-4" />
                                </Button>

                                <div className="space-y-4">
                                    <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                                        <div className="md:col-span-3">
                                            <label className="block text-xs font-semibold mb-1 opacity-70">Question {idx + 1}</label>
                                            <Input
                                                value={q.text}
                                                onChange={(e) => updateQuestion(idx, 'text', e.target.value)}
                                                placeholder="Enter question text"
                                                required
                                            />
                                        </div>
                                        <div>
                                            <label className="block text-xs font-semibold mb-1 opacity-70">Points</label>
                                            <Input
                                                type="number"
                                                value={q.points}
                                                onChange={(e) => updateQuestion(idx, 'points', Number(e.target.value))}
                                                min={0}
                                                required
                                            />
                                        </div>
                                    </div>

                                    <div>
                                        <label className="block text-xs font-semibold mb-1 opacity-70">Question Type</label>
                                        <div className="flex gap-2">
                                            {['MULTIPLE_CHOICE', 'SHORT_ANSWER', 'ESSAY'].map((t) => (
                                                <button
                                                    key={t}
                                                    type="button"
                                                    onClick={() => updateQuestion(idx, 'type', t as QuestionType)}
                                                    className={`px-3 py-1.5 rounded-lg text-xs font-semibold border transition-all ${q.type === t
                                                            ? 'bg-blue-600 border-blue-600 text-white shadow-sm'
                                                            : 'border-light-border dark:border-dark-border hover:bg-light-surface dark:hover:bg-dark-surface'
                                                        }`}
                                                >
                                                    {t.replace('_', ' ')}
                                                </button>
                                            ))}
                                        </div>
                                    </div>

                                    {q.type === 'MULTIPLE_CHOICE' && (
                                        <div className="space-y-3 pl-4 border-l-2 border-blue-200 dark:border-blue-800">
                                            <label className="block text-xs font-semibold opacity-70 italic">Options (Select the correct one)</label>
                                            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                                                {q.options.map((opt, optIdx) => (
                                                    <div key={optIdx} className="flex items-center gap-2">
                                                        <input
                                                            type="radio"
                                                            name={`correct-${idx}`}
                                                            checked={q.correctAnswer === opt && opt !== ''}
                                                            onChange={() => updateQuestion(idx, 'correctAnswer', opt)}
                                                            className="w-4 h-4 text-blue-600"
                                                            required={q.type === 'MULTIPLE_CHOICE'}
                                                        />
                                                        <Input
                                                            value={opt}
                                                            onChange={(e) => {
                                                                const newOpts = [...q.options];
                                                                newOpts[optIdx] = e.target.value;
                                                                updateQuestion(idx, 'options', newOpts);
                                                            }}
                                                            placeholder={`Option ${String.fromCharCode(65 + optIdx)}`}
                                                            className="h-8"
                                                            required={q.type === 'MULTIPLE_CHOICE'}
                                                        />
                                                    </div>
                                                ))}
                                            </div>
                                        </div>
                                    )}

                                    {(q.type === 'SHORT_ANSWER' || q.type === 'ESSAY') && (
                                        <div>
                                            <label className="block text-xs font-semibold mb-1 opacity-70">Correct Answer / Sample Answer</label>
                                            <Input
                                                value={q.correctAnswer}
                                                onChange={(e) => updateQuestion(idx, 'correctAnswer', e.target.value)}
                                                placeholder="What are you looking for in the answer?"
                                            />
                                        </div>
                                    )}
                                </div>
                            </div>
                        ))}
                    </div>

                    {questions.length === 0 && (
                        <div className="text-center py-12 border-2 border-dashed border-light-border dark:border-dark-border rounded-xl">
                            <p className="text-light-text-secondary dark:text-dark-text-secondary mb-4">No questions added yet.</p>
                            <Button type="button" variant="outline" onClick={addQuestion}>
                                <Plus className="h-4 w-4 mr-2" /> Add First Question
                            </Button>
                        </div>
                    )}
                </div>

                <div className="flex justify-end gap-3 pt-6 border-t border-light-border dark:border-dark-border">
                    <Button variant="ghost" onClick={onClose} type="button">Cancel</Button>
                    <Button type="submit" className="px-8" isLoading={isCreating}>
                        Save Assessment
                    </Button>
                </div>
            </form>
        </Modal>
    );
}
